/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class JSDrawTarget {
    constructor(width: number, height: number);
    get width(): number;
    get height(): number;
    fillRect(x: number, y: number, width: number, height: number, color: string): void;
    getBuffer(): Array<number>;
}
